//This jenkinsfile is used in this job: https://cmsvjenkins.rtp.raleigh.ibm.com:8443/job/Operational/job/Connect3x

pipeline {

agent {
    label 'cmschef1'
}

 stages{
     stage ('Cleanup the workspace') {
            steps {
                cleanWs deleteDirs: true, notFailBuild: true
            }
     }

    stage('Connect openvpn on jumphost') {
        steps {
          script {
            withCredentials([usernamePassword(credentialsId: 'sceptest_openvpn', passwordVariable: 'openvpn_psw', usernameVariable: 'openvpn_usr')]) {
              sh '''
              #!/usr/bin/bash
              gateway="cmschef1"
              export LC_openvpncfg="/etc/openvpn/client/sceptest.ovpn"
              logfile="/tmp/openvpn.log"
              set +e
              sudo ps -ef | grep openvpn | grep -v grep
              if [ $? == 0 ]; then
              		echo "Openvpn client is running on ${gateway}"
              		exit 0
              else
              		echo "Starting openvpn on ${gateway}. Please check ${logfile}"
                  echo -e "${openvpn_usr}\n${openvpn_psw}" > auth
                  chmod 600 auth
                  sudo openvpn --config "${LC_openvpncfg}" --log "${logfile}" --auth-user-pass auth --daemon && rm -rf auth
                  sleep 5
              fi
              set -e
              '''
            }
          }
		}
	}
	stage('Verify openvpn connection'){
       steps {
         script {
         withCredentials([usernamePassword(credentialsId: 'ibmaiacob1', passwordVariable: 'openvpn_psw', usernameVariable: 'openvpn_usr')]) {
           sh '''
           #!/usr/bin/bash
           ps -ef | grep openvpn | grep daemon | grep -v grep
           process=$?
           if [ ${process} == 0 ]; then
             echo "Openvpn client is connected"
           else
             echo "Trying to connect openvpn using another user"
             export LC_openvpncfg="/etc/openvpn/client/amm-ibmaiacob1.ovpn"
             echo -e "${openvpn_usr}\n${openvpn_psw}" > auth
             chmod 600 auth
             sudo openvpn --config "${LC_openvpncfg}" --log "${logfile}" --auth-user-pass auth --daemon && rm -rf auth
             sleep 5
           fi
           '''
           }
         }
      }
    }
	}
}
