---
- name: alerting rules file
  template:
    src: "alert.rules.j2"
    dest: "{{ prometheus_config_dir }}/rules/ansible_managed.rules"
    owner: 65534
    group: 65534
    mode: 0640
    #validate: "/usr/local/bin/promtool check rules %s"
  notify:
    - restart prometheus

- name: copy custom alerting rule files
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/rules/"
    owner: 65534
    group: 65534
    mode: 0640
    #validate: "/usr/local/bin/promtool check rules %s"
  with_fileglob: "{{ prometheus_alert_rules_files }}"
  notify:
    - restart prometheus
