version: '3.7'

services:
  master:
    build:
      context: ./jenkins-master/
      dockerfile: Dockerfile
    ports:
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

  proxy:
    image: ehazlett/docker-proxy:latest
    command: -i
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:
        aliases:
          - dockerproxy

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - jenkins-ssl:/etc/nginx/ssl
    networks:
      - jenkins-net

  slave:
    build:
      context: ./jenkins-slave/
      dockerfile: Dockerfile
volumes:
  jenkins-data:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/jenkins/data
  jenkins-log:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/jenkins/log
  jenkins-ssl:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/jenkins/ssl
networks:
  jenkins-net:
