metadata:
  labels:
    app: build
    name: docker-repo
spec:
  containers:
   - name: jnlp
     image: nexus.local.net:8123/jenkins-jnlp-slave:20200420
     env:
     - name: CONTAINER_ENV_VAR
       value: jnlp
   - name: maven
     image: maven:3.3.9-jdk-8-alpine
     command:
     - cat
     tty: true
     env:
     - name: CONTAINER_ENV_VAR
       value: maven
   - name: busybox
     image: busybox
     command:
     - cat
     tty: true
     env:
     - name: CONTAINER_ENV_VAR
       value: busybox
  imagePullSecrets:
  - name: docker-repo
