apiVersion: v1
kind: Service
metadata:
  name: glusterfs
  namespace: build
  labels:
    ep: gluster
spec:
  ports:
  - port: 1729
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs
  namespace: build
  labels:
    ep: gluster
subsets:
  - addresses:
      - ip: 192.168.100.3
    ports:
      - port: 1729
